{
 "title": "MeSQuaL board",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SQuaL Query",
   "type": "simple-angular-panel",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Query Results",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 0 },
   "targets": [
    { "rawSql": "SELECT *\nFROM MeSQuaLresults;" }
   ]
  },
  {
   "title": "Contract Types",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT  contractTypeName, dimensionName, outputType, language, functionPath\nFROM CONTRACTTYPE"
    }
   ]
  },
  {
   "title": "Data Quality Checks",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  elementGranularity, elementId, contractType, dimensionName, udfResult\nFROM UDFresults\nWHERE violation = 1 AND\nelementId != 'row'\nAND queryTimestamp = (SELECT max(queryTimestamp) FROM UDFresults)"
    }
   ]
  },
  {
   "title": "Monitoring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(queryTimestamp) as time_sec,\n  udfResult as value,\n  CONCAT(dimensionname,\",\",elementGranularity,\":\",elementId) as metric\nFROM UDFresults\nWHERE $__timeFilter(queryTimestamp) AND elementGranularity != 'row' AND queryId IN (SELECT DISTINCT queryId FROM UDFresults WHERE queryTimestamp = (SELECT MAX(queryTimestamp) FROM UDFresults))\nORDER BY queryTimestamp ASC\n"
    }
   ]
  },
  {
   "title": "Monitoring: last checkpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(queryTimestamp) as time_sec,\n  udfResult as value,\n  CONCAT(dimensionname,\",\",elementGranularity,\":\",elementId) as metric\nFROM UDFresults\nWHERE $__timeFilter(queryTimestamp) AND elementGranularity != 'row' AND queryTimestamp = (SELECT MAX(queryTimestamp) FROM UDFresults)\nORDER BY queryTimestamp ASC\n"
    }
   ]
  },
  {
   "title": "Contracts",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 13 },
   "targets": [
    { "rawSql": "SELECT *\nFROM CONTRACT" }
   ]
  },
  {
   "title": "Queries",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 17 },
   "targets": [
    { "rawSql": "SELECT *\nFROM MeSQuaLqueries" }
   ]
  },
  {
   "title": "Query & Check Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 20 },
   "targets": [
    { "rawSql": "SELECT *\nFROM UDFresults" }
   ]
  },
  {
   "title": "Tables",
   "type": "table",
   "description": "List of tables in the DBMS",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "  SELECT TABLE_SCHEMA AS `database`,\n         TABLE_NAME AS `table`\n    FROM information_schema.TABLES\n   WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'mysql', 'sys','phpmyadmin')\n   ORDER BY TABLE_SCHEMA, TABLE_NAME"
    }
   ]
  }
 ]
}